### PR TITLE
Update download link to 0.3.1.

### PR DESCRIPTION
**Pull request by mrstegeman**

### CODE REVIEW

**Comment by dhylands** [comment]
I'm just in the process of creating v0.3.2 which uses the latest raspbian base image to support the 3B+

**Comment by dhylands** [comment]
Sigh - looks like it will need some changes.

**Comment by hobinjk** [comment]
There's an issue with 0.3.1 because I forgot that we need node 8 instead of node 7 so this can't happen quite yet.

**Comment by dhylands** [comment]
ok - I updated make-prep.sh to set the country code by default and created a new 0.3.1 base and final images. The final image should also work on the 3B+

**Pull request merged**
